/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 NewPlayer.glb -T 
Files: NewPlayer.glb [5.52MB] > F:\My Documents\Sites games\treasure-dive\public\models\NewPlayer-transformed.glb [621.1KB] (89%)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModelNewPlayer(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/NewPlayer-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // 1. Get the name of the first animation from the raw array
    const firstAnimationName = animations[0]?.name;

    // 2. Fall back to props.action if provided, otherwise use the first animation name
    const activeActionName = props.action || firstAnimationName;

    // 3. Play the animation using its string name key
    if (activeActionName && actions[activeActionName]) {
      actions[activeActionName].reset().fadeIn(0.5).play();
    }

    return () => {
      if (activeActionName && actions[activeActionName]) {
        actions[activeActionName].fadeOut(0.5);
      }
    };
  }, [actions, animations, props.action]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="Soldier_body" geometry={nodes.Soldier_body.geometry} material={materials['Soldier_body1.001']} skeleton={nodes.Soldier_body.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="Soldier_head" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh name="Soldier_head_1" geometry={nodes.Soldier_head_1.geometry} material={materials['Soldier_body1.001']} skeleton={nodes.Soldier_head_1.skeleton} />
          <skinnedMesh name="Soldier_head_2" geometry={nodes.Soldier_head_2.geometry} material={materials.Soldier_head6} skeleton={nodes.Soldier_head_2.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/NewPlayer-transformed.glb')
