/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Rock.glb -T 
Files: Rock.glb [28.99KB] > F:\My Documents\Sites games\treasure-dive\public\models\Rock-transformed.glb [6.67KB] (77%)
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


export function ModelRock(props) {
  const { nodes, materials } = useGLTF('models/Rock-transformed.glb')

  // Clone and override material color only once
  const rockMaterial = useMemo(() => {
    if (!materials.Atlas) return undefined;
    const mat = materials.Atlas.clone();
    // Shift color 100% towards the target to keep original shading/texture influence
    mat.color.lerp(new THREE.Color('#e6ff03'), 1);
    return mat;
  }, [materials.Atlas]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_4.geometry} material={rockMaterial} scale={100} />
    </group>
  )
}

useGLTF.preload('models/Rock-transformed.glb')
