/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 models\ship_dark.gltf --output output\ship_dark.js --transform --keepnames --shadows 
Files: models\ship_dark.gltf [30.55KB] > F:\My Documents\Articles Media\AMCOT\Models\Kenny\kenney_pirate-kit\JSX\output\ship_dark-transformed.glb [30.72KB] (-1%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Pirate/Models/ship_dark.glb`;

export function ModelKennyNLPirateShipDark(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <group name="ship_dark_8angles" position={[4.27, 0, 0.014]}>
        <mesh name="ship_dark_8angles_1" castShadow receiveShadow geometry={nodes.ship_dark_8angles_1.geometry} material={materials.PaletteMaterial002} />
        <mesh name="ship_dark_8angles_2" castShadow receiveShadow geometry={nodes.ship_dark_8angles_2.geometry} material={materials.PaletteMaterial001} />
      </group>
    </group>
  )
}

useGLTF.preload(link)
